const defaultTheme = require('tailwindcss/defaultTheme');

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class', '[data-mantine-color-scheme="dark"]'],
  content: ['./public/index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--mantine-font-family)'],
      },
      spacing: {
        xl: 'var(--mantine-spacing-xl)',
        lg: 'var(--mantine-spacing-lg)',
        md: 'var(--mantine-spacing-md)',
        sm: 'var(--mantine-spacing-sm)',
        xs: 'var(--mantine-spacing-xs)',
      },
      fontSize: {
        xs: ['var(--mantine-font-size-xs)', 'var(--mantine-line-height-xs)'],
        sm: ['var(--mantine-font-size-sm)', 'var(--mantine-line-height-sm)'],
        md: ['var(--mantine-font-size-md)', 'var(--mantine-line-height-md)'],
        lg: ['var(--mantine-font-size-lg)', 'var(--mantine-line-height-lg)'],
        xl: ['var(--mantine-font-size-xl)', 'var(--mantine-line-height-xl)'],
      },
      borderRadius: {
        xs: 'var(--mantine-radius-xs,0.125rem)',
        sm: 'var(--mantine-radius-sm,0.25rem)',
        md: 'var(--mantine-radius-md,0.5rem)',
        lg: 'var(--mantine-radius-lg,1rem)',
        xl: 'var(--mantine-radius-xl,2rem)',
        DEFAULT: 'var(--mantine-radius-default,0.25rem)',
      },
      colors: {
        gray: {
          0: 'var(--mantine-color-gray-0,#F8F9FA)',
          1: 'var(--mantine-color-gray-1,#F1F3F5)',
          2: 'var(--mantine-color-gray-2,#E9ECEF)',
          3: 'var(--mantine-color-gray-3,#DEE2E6)',
          4: 'var(--mantine-color-gray-4,#CED4DA)',
          5: 'var(--mantine-color-gray-5,#ADB5BD)',
          6: 'var(--mantine-color-gray-6,#868E96)',
          7: 'var(--mantine-color-gray-7,#495057)',
          8: 'var(--mantine-color-gray-8,#343A40)',
          9: 'var(--mantine-color-gray-9,#212529)',
        },
        dark: {
          0: 'var(--mantine-color-dark-0,#C1C2C5)',
          1: 'var(--mantine-color-dark-1,#A6A7AB)',
          2: 'var(--mantine-color-dark-2,#909296)',
          3: 'var(--mantine-color-dark-3,#5C5F66)',
          4: 'var(--mantine-color-dark-4,#373A40)',
          5: 'var(--mantine-color-dark-5,#2C2E33)',
          6: 'var(--mantine-color-dark-6,#25262B)',
          7: 'var(--mantine-color-dark-7,#1A1B1E)',
          8: 'var(--mantine-color-dark-8,#141517)',
          9: 'var(--mantine-color-dark-9,#101113)',
        },
        blue: {
          0: 'var(--mantine-color-blue-0,#E7F5FF)',
          1: 'var(--mantine-color-blue-1,#D0EBFF)',
          2: 'var(--mantine-color-blue-2,#A5D8FF)',
          3: 'var(--mantine-color-blue-3,#74C0FC)',
          4: 'var(--mantine-color-blue-4,#4DABF7)',
          5: 'var(--mantine-color-blue-5,#339AF0)',
          6: 'var(--mantine-color-blue-6,#228BE6)',
          7: 'var(--mantine-color-blue-7,#1C7ED6)',
          8: 'var(--mantine-color-blue-8,#1971C2)',
          9: 'var(--mantine-color-blue-9,#1864AB)',
        },
        red: {
          0: 'var(--mantine-color-red-0,#FFF5F5)',
          1: 'var(--mantine-color-red-1,#FFE3E3)',
          2: 'var(--mantine-color-red-2,#FFC9C9)',
          3: 'var(--mantine-color-red-3,#FFA8A8)',
          4: 'var(--mantine-color-red-4,#FF8787)',
          5: 'var(--mantine-color-red-5,#FF6B6B)',
          6: 'var(--mantine-color-red-6,#FA5252)',
          7: 'var(--mantine-color-red-7,#F03E3E)',
          8: 'var(--mantine-color-red-8,#E03131)',
          9: 'var(--mantine-color-red-9,#C92A2A)',
        },
        black: 'var(--mantine-color-black,#000000)',
        white: 'var(--mantine-color-white,#FFFFFF)',
        'blue-light': 'var(--mantine-color-blue-light,#228be61a)',
        'blue-light-color': 'var(--mantine-color-blue-light-color,#228be6)',
        'blue-light-hover': 'var(--mantine-primary-color-light-hover)',
        dimmed: 'var(--mantine-color-dimmed,#868e96)',
        'primary-filled': 'var(--mantine-primary-color-filled)',
        bright: 'var(--mantine-color-bright,#fff)',
      },
    },
  },
  corePlugins: {
    preflight: false,
  },
  plugins: [require('@tailwindcss/container-queries')],
};
